import type { ScholarProfile, StudentProfile } from "@mobiliza/db/schema";

const scholars: ScholarProfile[] = [
	{
		id: "1",
		userId: "1",
		enrollment: "2020123456",
		course: "Engenharia de Software",
		campus: "Campus A",
		phone: "11987654321",
		cpf: "123.456.789-00",
		shift: "morning",
		isApproved: true,
		approvedAt: new Date(),
		approvedBy: "admin",
		isAvailable: true,
		createdAt: new Date(),
		updatedAt: new Date(),
		isActive: true,
	},
	{
		id: "2",
		userId: "2",
		enrollment: "2020123457",
		course: "Sistemas de Informação",
		campus: "Campus B",
		phone: "11988887777",
		cpf: "234.567.890-11",
		shift: "afternoon",
		isApproved: true,
		approvedAt: new Date(),
		approvedBy: "admin",
		isAvailable: false,
		createdAt: new Date(),
		updatedAt: new Date(),
		isActive: true,
	},
	{
		id: "3",
		userId: "3",
		enrollment: "2020123458",
		course: "Ciência da Computação",
		campus: "Campus C",
		phone: "11999990000",
		cpf: "345.678.901-22",
		shift: "afternoon",
		isApproved: false,
		approvedAt: null,
		approvedBy: null,
		isAvailable: true,
		createdAt: new Date(),
		updatedAt: new Date(),
		isActive: true,
	},
	{
		id: "4",
		userId: "4",
		enrollment: "2020123459",
		course: "Engenharia de Computação",
		campus: "Campus D",
		phone: "11876543210",
		cpf: "456.789.012-33",
		shift: "morning",
		isApproved: true,
		approvedAt: new Date(),
		approvedBy: "coordenacao",
		isAvailable: true,
		createdAt: new Date(),
		updatedAt: new Date(),
		isActive: true,
	},
];

const students: StudentProfile[] = [
	{
		id: "1",
		userId: "5",
		enrollment: "2021123456",
		course: "Ciência da Computação",
		campus: "Campus A.C. Simões",
		phone: "11987654321",
		shift: "morning",
		createdAt: new Date(),
		gender: "male",
		isActive: true,
		nickname: "Eduardo",
		updatedAt: new Date(),
		attendanceNotes: null,
		simplifiedInterface: false,
	},
	{
		id: "2",
		userId: "6",
		enrollment: "2021123457",
		course: "Engenharia Florestal",
		campus: "Campus A.C. Simões",
		phone: "11988881234",
		shift: "afternoon",
		createdAt: new Date(),
		gender: "female",
		isActive: true,
		nickname: "Ana",
		updatedAt: new Date(),
		attendanceNotes: null,
		simplifiedInterface: true,
	},
	{
		id: "3",
		userId: "7",
		enrollment: "2021123458",
		course: "Sistemas de Informação",
		campus: "Campus CECA",
		phone: "11977772345",
		shift: "night",
		createdAt: new Date(),
		gender: "male",
		isActive: true,
		nickname: "Lucas",
		updatedAt: new Date(),
		attendanceNotes: null,
		simplifiedInterface: false,
	},
	{
		id: "4",
		userId: "8",
		enrollment: "2021123459",
		course: "Ciência da Computação",
		campus: "Campus A.C. Simões",
		phone: "11966663456",
		shift: "morning",
		createdAt: new Date(),
		gender: "female",
		isActive: false,
		nickname: "Beatriz",
		updatedAt: new Date(),
		attendanceNotes: "Em troca de turno",
		simplifiedInterface: true,
	},
	{
		id: "5",
		userId: "9",
		enrollment: "2021123460",
		course: "Engenharia de Computação",
		campus: "Campus Arapiraca",
		phone: "11955554567",
		shift: "afternoon",
		createdAt: new Date(),
		gender: "male",
		isActive: true,
		nickname: "Pedro",
		updatedAt: new Date(),
		attendanceNotes: null,
		simplifiedInterface: false,
	},
	{
		id: "6",
		userId: "10",
		enrollment: "2021123461",
		course: "Matemática",
		campus: "Campus A.C. Simões",
		phone: "11944445678",
		shift: "night",
		createdAt: new Date(),
		gender: "female",
		isActive: true,
		nickname: "Mariana",
		updatedAt: new Date(),
		attendanceNotes: null,
		simplifiedInterface: true,
	},
];

export { scholars, students };
