import { pgEnum } from "drizzle-orm/pg-core";

export const courseValues = [
	"Administração",
	"Administração Pública",
	"Agroecologia",
	"Agronomia",
	"Arquitetura e Urbanismo",
	"Biblioteconomia",
	"Ciência da Computação",
	"Ciências Biológicas",
	"Ciências Contábeis",
	"Ciências Econômicas",
	"Ciências Sociais",
	"Ciências: Biologia, Física e Química",
	"Comunicação Social (Jornalismo)",
	"Comunicação Social (Relações Públicas)",
	"Dança",
	"Design",
	"Direito",
	"Educação Física",
	"Enfermagem",
	"Engenharia Ambiental e Sanitária",
	"Engenharia Civil",
	"Engenharia de Agrimensura",
	"Engenharia de Computação",
	"Engenharia de Energia",
	"Engenharia de Pesca",
	"Engenharia de Petróleo",
	"Engenharia de Produção",
	"Engenharia Elétrica",
	"Engenharia Florestal",
	"Engenharia Química",
	"Farmácia",
	"Filosofia",
	"Física",
	"Geografia",
	"História",
	"Inteligência Artificial",
	"Jornalismo",
	"Letras",
	"Letras (Espanhol)",
	"Letras (Francês)",
	"Letras (Inglês)",
	"Letras (Português)",
	"Letras Libras",
	"Matemática",
	"Medicina",
	"Medicina Veterinária",
	"Meteorologia",
	"Música",
	"Música (Canto)",
	"Nutrição",
	"Odontologia",
	"Pedagogia",
	"Psicologia",
	"Química",
	"Química Tecnológica e Industrial",
	"Relações Públicas",
	"Serviço Social",
	"Sistemas de Informação",
	"Teatro",
	"Turismo",
	"Zootecnia",
] as const;

export const courseEnum = pgEnum("course", courseValues);
