export { RoutePreview } from "../route-preview";
export { DetailsSection } from "../section";
export { DetailsSidebar } from "./details-sidebar";
export { ScholarDetailsSidebar } from "./scholar/sidebar";
export { ScholarDetailsTrigger } from "./scholar/trigger";
export { ServiceDetailsSidebar } from "./service/sidebar";
export { ServiceDetailsTrigger } from "./service/trigger";
export { StudentDetailsSidebar } from "./student/sidebar";
export { StudentDetailsTrigger } from "./student/trigger";
